export const DEFAULT_LIFE_AREAS = [
  { name: 'Spiritual', slug: 'spiritual', color: '#5B6C8F', icon: 'sparkle', sortOrder: 1 },
  { name: 'Health', slug: 'health', color: '#3D7A5A', icon: 'heart', sortOrder: 2 },
  { name: 'English', slug: 'english', color: '#4A6FA5', icon: 'book', sortOrder: 3 },
  { name: 'Skill Development', slug: 'skill', color: '#6B5B95', icon: 'code', sortOrder: 4 },
  { name: 'Career / Work', slug: 'work', color: '#8A6D3B', icon: 'briefcase', sortOrder: 5 },
  { name: 'Personal', slug: 'personal', color: '#6E6A62', icon: 'user', sortOrder: 6 },
] as const;

export const DEFAULT_HABITS = [
  {
    name: 'Prayer',
    slugArea: 'spiritual',
    frequency: 'daily' as const,
    target: 1,
    unit: 'completion' as const,
    captureStyle: 'complete' as const,
    selectedDays: [] as number[],
  },
  {
    name: 'Bible Reading',
    slugArea: 'spiritual',
    frequency: 'daily' as const,
    target: 1,
    unit: 'completion' as const,
    captureStyle: 'complete' as const,
    selectedDays: [] as number[],
  },
  {
    name: 'Exercise',
    slugArea: 'health',
    frequency: 'daily' as const,
    target: 30,
    unit: 'minutes' as const,
    captureStyle: 'duration' as const,
    selectedDays: [] as number[],
  },
  {
    name: 'English',
    slugArea: 'english',
    frequency: 'daily' as const,
    target: 30,
    unit: 'minutes' as const,
    captureStyle: 'duration' as const,
    selectedDays: [] as number[],
  },
  {
    name: 'Skill Development',
    slugArea: 'skill',
    frequency: 'daily' as const,
    target: 60,
    unit: 'minutes' as const,
    captureStyle: 'learning' as const,
    selectedDays: [] as number[],
  },
  {
    name: 'Work',
    slugArea: 'work',
    frequency: 'weekdays' as const,
    target: 1,
    unit: 'completion' as const,
    captureStyle: 'complete' as const,
    selectedDays: [1, 2, 3, 4, 5],
  },
];
